// Reddit OAuth config
export const REDDIT_CLIENT_ID = process.env.NEXT_PUBLIC_REDDIT_CLIENT_ID || '';
export const REDDIT_REDIRECT_URI = process.env.NEXT_PUBLIC_REDDIT_REDIRECT_URI || 'http://localhost:3000/auth/callback';

// Subreddit mappings for each sport
export const NFL_SUBREDDITS = [
  'nfl',
  // Team subreddits
  'AZCardinals',
  'falcons',
  'ravens',
  'buffalobills',
  'panthers',
  'CHIBears',
  'bengals',
  'Browns',
  'cowboys',
  'denverbroncos',
  'detroitlions',
  'GreenBayPackers',
  'Texans',
  'Colts',
  'Jaguars',
  'KansasCityChiefs',
  'raiders',
  'Chargers',
  'LosAngelesRams',
  'miamidolphins',
  'minnesotavikings',
  'Patriots',
  'Saints',
  'NYGiants',
  'nyjets',
  'eagles',
  'steelers',
  '49ers',
  'Seahawks',
  'buccaneers',
  'Tennesseetitans',
  'Commanders',
];

export const NBA_SUBREDDITS = [
  'nba',
  // Team subreddits
  'AtlantaHawks',
  'bostonceltics',
  'GoNets',
  'CharlotteHornets',
  'chicagobulls',
  'clevelandcavs',
  'Mavericks',
  'denvernuggets',
  'DetroitPistons',
  'warriors',
  'rockets',
  'pacers',
  'LAClippers',
  'lakers',
  'memphisgrizzlies',
  'heat',
  'MkeBucks',
  'timberwolves',
  'NOLAPelicans',
  'NYKnicks',
  'Thunder',
  'OrlandoMagic',
  'sixers',
  'suns',
  'ripcity',
  'kings',
  'NBASpurs',
  'torontoraptors',
  'UtahJazz',
  'washingtonwizards',
];

// Team abbreviation to subreddit mapping
export const NFL_TEAM_SUBREDDITS: Record<string, string> = {
  'ARI': 'AZCardinals',
  'ATL': 'falcons',
  'BAL': 'ravens',
  'BUF': 'buffalobills',
  'CAR': 'panthers',
  'CHI': 'CHIBears',
  'CIN': 'bengals',
  'CLE': 'Browns',
  'DAL': 'cowboys',
  'DEN': 'denverbroncos',
  'DET': 'detroitlions',
  'GB': 'GreenBayPackers',
  'HOU': 'Texans',
  'IND': 'Colts',
  'JAX': 'Jaguars',
  'KC': 'KansasCityChiefs',
  'LV': 'raiders',
  'LAC': 'Chargers',
  'LA': 'LosAngelesRams',
  'LAR': 'LosAngelesRams',
  'MIA': 'miamidolphins',
  'MIN': 'minnesotavikings',
  'NE': 'Patriots',
  'NO': 'Saints',
  'NYG': 'NYGiants',
  'NYJ': 'nyjets',
  'PHI': 'eagles',
  'PIT': 'steelers',
  'SF': '49ers',
  'SEA': 'Seahawks',
  'TB': 'buccaneers',
  'TEN': 'Tennesseetitans',
  'WAS': 'Commanders',
};

export const NBA_TEAM_SUBREDDITS: Record<string, string> = {
  'ATL': 'AtlantaHawks',
  'BOS': 'bostonceltics',
  'BKN': 'GoNets',
  'CHA': 'CharlotteHornets',
  'CHI': 'chicagobulls',
  'CLE': 'clevelandcavs',
  'DAL': 'Mavericks',
  'DEN': 'denvernuggets',
  'DET': 'DetroitPistons',
  'GS': 'warriors',
  'GSW': 'warriors',
  'HOU': 'rockets',
  'IND': 'pacers',
  'LAC': 'LAClippers',
  'LAL': 'lakers',
  'MEM': 'memphisgrizzlies',
  'MIA': 'heat',
  'MIL': 'MkeBucks',
  'MIN': 'timberwolves',
  'NOP': 'NOLAPelicans',
  'NO': 'NOLAPelicans',
  'NYK': 'NYKnicks',
  'NY': 'NYKnicks',
  'OKC': 'Thunder',
  'ORL': 'OrlandoMagic',
  'PHI': 'sixers',
  'PHX': 'suns',
  'POR': 'ripcity',
  'SAC': 'kings',
  'SAS': 'NBASpurs',
  'SA': 'NBASpurs',
  'TOR': 'torontoraptors',
  'UTA': 'UtahJazz',
  'WAS': 'washingtonwizards',
};
